# local 환경
---
spring:
  profiles:
    active: local

# local 환경
---
spring.profiles: local
spring.profiles.include: real-db, appconf
spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    jdbc:
      sqlonly: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 5000

pagehelper:
  helper-dialect: mysql
  reasonable: false
  supportMethodsArguments: true
