# local 환경
---
spring:
  profiles:
    active: local
#  datasource:
#    data: classpath:data-h2.sql # 시작할때 실행시킬 script
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true

# local 환경
---
spring.profiles: local
spring.profiles.include: real-db, appconf
spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    jdbc:
      sqlonly: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 5000

pagehelper:
  helper-dialect: mysql
  reasonable: false
  supportMethodsArguments: true

---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082