on:
  push:
    branches:
      - master

name: Deploy String boot to Amazon EC2
env:
  PROJECT_NAME: snapcollector

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Make zip file
        run: zip -r snapcollector *
        shell: bash
        
      - name: Make zip file2
        run: mkdir -p deploy
        shell: bash
        
      - name: MAke zip file3
        run: mv snapcollector.zip deploy/snapcollector.zip
        shell: bash

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp --region ap-northeast-2 deploy/snapcollector.zip s3://snap-springservice-deploy

      - name: Code Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws deploy create-deployment --application-name snap-springservice --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name dev --s3-location bucket=snap-springservice-deploy,bundleType=zip,key=snapcollector.zip
